FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY ./server /app/server

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

EXPOSE 50051

CMD ["python", "server/main.py"]
