version: "3.9"

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: grpc-server
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongo

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rest-api
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - rest-api

volumes:
  mongo-data:
