# Use Python 3.11 slim as base image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app

# Copy only necessary files
COPY ./server /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose gRPC port
EXPOSE 50051

# Run server
CMD ["python", "main.py"]
